# url: http://localhost:3000
#
url: http://www.codefurniture.us
# baseurl: http://www.codefurniture.us
name: Code Furniture
description: "Western Nationalism"
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

gems:
  - jekyll-octicons

# Collections
collections:
  education:
    output: true
    permalink: '/education/:path/'    
  books:
    output: true
    output_ext: .html
    permalink: /books/:path/

locale: en_US # language_territory is the default
avatar: "cf-avatar.png" # make twitter summary card compatible
twitter: "codefurniture" # Don't include @

csv:
  education:
    source: https://docs.google.com/spreadsheets/u/1/d/1rFnkM9rrhwmo5eTwhEPordgucf-iNACnzc6E78elkaM/export?format=csv
    slug: organisation_name
