# url: http://localhost:3000
#
url: http://www.codefurniture.us
# baseurl: http://www.codefurniture.us
name: Code Furniture
description: "Western Nationalism"
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

gems:
  - jekyll-octicons

# Collections
collections:
  books:
    output: true
    output_ext: .html
    permalink: /books/:path/

locale: en_US # language_territory is the default
avatar: "cf-avatar.jpg"
twitter: "codefurniture" # Don't include @
