# Site settings
title: Code Furniture
version: "v1"
email: codefurniture@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Agency for Meaningful Propaganda
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.codefurniture.us" # the base hostname & protocol for your site
#url: "" # the base hostname & protocol for your site
twitter_username: codefurniture
github_username:  codefurniture

# Build settings
markdown: kramdown

# Tachyons Version
tv: "4.6.1"

# Exclude this stuff
exclude: [node_modules, gulpfile.js]

# Gems
gems:
  - jekyll-seo-tag
