# url: http://localhost:3000
url: www.codefurniture.us
name: CF
description: "Western Nationalism"
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

gems:
  - jekyll-octicons

# Collections
collections:
  books:
    output: true
    output_ext: .html
    permalink: /books/:path/
